"""add readme_markdown to analyses

Revision ID: ae1ec85761ad
Revises: f42b7ba0697d
Create Date: 2026-08-08 16:56:52.152420
"""
from alembic import op
import sqlalchemy as sa



revision = 'ae1ec85761ad'
down_revision = 'f42b7ba0697d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('readme_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'readme_markdown')
    # ### end Alembic commands ###
